version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: nodejs_sequelize_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nodejs_sequelize_network

  app:
    build:
      context: .
      no_cache: true
    container_name: nodejs_sequelize_app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/user/src/app
      - app_node_modules:/app/node_modules
    command: npm run dev
    restart: always
    networks:
      - nodejs_sequelize_network

volumes:
  postgres_data:
  app_node_modules:


networks:
  nodejs_sequelize_network:
    driver: bridge
